---
wireguard_router_public_key: jZq5BiyMWNEreaihpnrjh3quL/oYDaOk2JY1/J24kx0=
wireguard_client_public_key: v/J15qL+m8VciXNanhMzbEXq4Hk1IYbsrUVVFL9ak20=
wireguard_client_2_public_key: 2U+mm1QRcZNL6YsQ5JwA8KdEG+v4q6EYao2oT4um3z0=
