---
- name: Set up Ubuntu server
  hosts: ubuntu_server
  roles:
    - role: ubuntu_configure_netplan
      vars:
        netplan_type: server
    - role: ubuntu_set_up_nginx
      vars:
        domain: some-domain.com
    - role: ubuntu_configure_ufw
      vars:
        ufw_allowed_ports:
          - 22
          - 80
          - 443
