---
- name: Set up Ubuntu server
  hosts: ubuntu_server
  vars:
    netplan_type: server
    domain: server.lab
    ubuntu_configure_ufw_allowed_tcp_ports:
      - 22
      - 80
      - 443
  roles:
    - ubuntu_configure_netplan
    - ubuntu_set_up_nginx
    - ubuntu_configure_ufw
