---
- name: Set up Ubuntu client
  hosts: ubuntu_client_2
  vars:
    netplan_type: client
    wireguard_role: client2
    ipsec_role: client-2
  roles:
    # - ubuntu_desktop
    - ubuntu_configure_netplan
    - set_up_wireguard
    - set_up_ipsec
