connections {
    vpn-router {
        left=%defaultroute
        leftsubnet=10.0.0.0/24
        right=10.0.1.1
        rightsubnet=10.0.1.0/24
        # psk = pre shared key
        authby=psk
        # the pre shared key in question
        key=supersecret
        # Connection is added to StrongSwan’s list of connections but not automatically initiated
        # Useful for a server/router that listens for incoming connections.
        # Server waits for a client to connect — it does not try to initiate the tunnel itself
        auto=start
    }
}
