connections {
    vpn-client {
        left=10.0.1.1
        leftsubnet=10.0.1.0/24
        right=%any
        rightsubnet=10.0.0.0/24
        # psk = pre shared key
        authby=psk
        # the pre shared key in question
        key=supersecret
        # Connection is added and immediately initiated
        # Useful for clients that must actively connect to a server
        auto=add
    }
}
