---
- name: Add netplan file
  become: true
  ansible.builtin.copy:
    src: "{{ netplan_type }}.yml"
    dest: /etc/netplan/00-lab-net-{{ netplan_type }}.yaml
    owner: root
    group: root
    mode: "0644"

- name: Test netplan config
  become: true
  ansible.builtin.command: netplan try --timeout 10
  register: netplan_test
  failed_when: netplan_test.rc != 0
  changed_when: false

- name: Apply netplan
  become: true
  ansible.builtin.command: netplan apply
  changed_when: false
