---
- name: Add netplan file
  become: true
  ansible.builtin.copy:
    src: "{{ netplan_type }}.yml"
    dest: /etc/netplan/00-lab-net-{{ netplan_type }}.yaml
    owner: root
    group: root
    mode: "0600"

- name: Generate netplan configuration
  become: true
  ansible.builtin.command: netplan generate
  changed_when: false

- name: Apply netplan
  become: true
  ansible.builtin.command: netplan apply
  changed_when: false
