---
ubuntu:
  hosts:
    ubuntu_client:
      ansible_host: host_ip_address
      ansible_user: ubuntu
      ansible_become_pass: ubuntu
    ubuntu_router:
      ansible_host: host_ip_address
      ansible_user: ubuntu
      ansible_become_pass: ubuntu
    ubuntu_server:
      ansible_host: host_ip_address
      ansible_user: ubuntu
      ansible_become_pass: ubuntu

windows:
  hosts:
    client:
      ansible_host:
      ansible_user: vboxuser
    router:
      ansible_host:
      ansible_user: vboxuser
    webserver:
      ansible_host:
      ansible_user: vboxuser
